"""
server.py — FastAPI backend for the A-Level Physics AI Tutor web app.

Run with:
    uvicorn server:app --reload
"""
import json
from collections import defaultdict
from typing import AsyncGenerator

import src.config as _config  # triggers dotenv load
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import StreamingResponse
from pydantic import BaseModel, Field

from src.embedder import embed_query
from src.openrouter import yield_answer, yield_chat, generate_quiz
from src.pinecone_store import get_client, query_index


def _is_readable(text: str) -> bool:
    """Return True if the chunk contains mostly readable text."""
    if not text or len(text) < 20:
        return False
    alphanum = sum(c.isalnum() or c.isspace() for c in text)
    return (alphanum / len(text)) >= 0.6

app = FastAPI(title="Physics RAG API")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["https://tiny-wisp-c3d4e3.netlify.app", "http://localhost:3000", "http://127.0.0.1:3000"],
    allow_methods=["*"],
    allow_headers=["*"],
)

from fastapi.staticfiles import StaticFiles
from pathlib import Path as _Path

_PAPERS_DIR = _Path("./papers")
_PAPERS_DIR.mkdir(exist_ok=True)
app.mount("/papers", StaticFiles(directory=_PAPERS_DIR), name="papers")

# Initialise Pinecone client once at startup
_pc = get_client()

# Simple in-memory embedding cache (survives for the lifetime of the process)
_embed_cache: dict[str, list[float]] = {}

# Cache for library sources — avoids querying Pinecone top_k=10000 on every page visit
_sources_cache: list[dict] | None = None

# Load Drive resource map (filename → preview URL) generated by scan_drive.py
_DRIVE_MAP_PATH = _Path("drive_resources.json")
_drive_map: dict[str, str] = {}
if _DRIVE_MAP_PATH.exists():
    import json as _json
    _drive_map = _json.loads(_DRIVE_MAP_PATH.read_text())

def _cached_embed(question: str) -> list[float]:
    key = question.strip().lower()
    if key not in _embed_cache:
        _embed_cache[key] = embed_query(question)
        if len(_embed_cache) > 500:          # cap memory usage
            _embed_cache.pop(next(iter(_embed_cache)))
    return _embed_cache[key]

_GREETING_STARTERS = {"hi", "hey", "hello", "yo", "sup", "bro", "wassup", "wsg", "hola",
                      "howdy", "morning", "evening", "afternoon", "heyy", "heyyy", "hii"}

def _is_greeting(text: str) -> bool:
    cleaned = text.strip().lower().rstrip("!?.")
    words = cleaned.split()
    # Short casual message (≤6 words) that starts with or is a greeting word
    if not words:
        return False
    return len(words) <= 6 and words[0] in _GREETING_STARTERS


# ---------------------------------------------------------------------------
# Models
# ---------------------------------------------------------------------------

class ChatMessage(BaseModel):
    role: str  # "user" or "assistant"
    content: str


class QueryRequest(BaseModel):
    question: str = Field(..., min_length=1, max_length=1000)
    top_k: int = Field(3, ge=1, le=20)
    language: str = Field("en", pattern=r"^[a-z]{2}$")
    history: list[ChatMessage] = Field(default_factory=list)


class QuizRequest(BaseModel):
    topic: str = Field(..., min_length=1, max_length=300)
    difficulty: str = Field("medium", pattern=r"^(easy|medium|hard)$")
    num_questions: int = Field(5, ge=1, le=20)
    language: str = Field("en", pattern=r"^[a-z]{2}$")


# ---------------------------------------------------------------------------
# Endpoints
# ---------------------------------------------------------------------------

@app.on_event("startup")
async def warmup():
    """Pre-warm the Gemini embedding connection so the first user query isn't slow."""
    try:
        _cached_embed("warmup")
    except Exception:
        pass  # Don't crash startup if warmup fails

@app.get("/api/health")
def health():
    return {"status": "ok"}


@app.post("/api/query")
def query(req: QueryRequest):
    """
    SSE streaming endpoint.

    Events sent:
      data: {"type": "chunk",   "content": "..."}
      data: {"type": "sources", "sources": [...]}
      data: {"type": "done"}
    """
    if not req.question.strip():
        raise HTTPException(status_code=400, detail="question must not be empty")

    def event_stream() -> AsyncGenerator:
        # Signal that we're thinking (shows spinner immediately)
        yield f"data: {json.dumps({'type': 'thinking'})}\n\n"

        # Handle greetings/casual chat directly — skip Pinecone
        if _is_greeting(req.question):
            for delta in yield_chat(req.question, req.language):
                yield f"data: {json.dumps({'type': 'chunk', 'content': delta})}\n\n"
            yield f"data: {json.dumps({'type': 'done'})}\n\n"
            return

        # 1. Build search query — enrich vague follow-ups with the best topic from history
        _VAGUE = {"this", "it", "that", "these", "those", "same", "more", "answer",
                  "question", "questions", "solution", "working", "steps", "hint", "help",
                  "example", "examples", "elaborate", "further", "continue", "again", "another"}
        _FILLER = {"can", "u", "you", "give", "me", "more", "be", "explanable", "explain", "tell", "about",
                   "a", "an", "the", "is", "what", "how", "why", "ok", "okay", "sure", "yes", "no", "and"}
        words = set(req.question.lower().split())
        is_vague = len(req.question.split()) <= 12 and bool(words & _VAGUE)
        if is_vague and req.history:
            # Find the most substantive user message (longest, not a filler phrase)
            user_msgs = [m.content for m in req.history if m.role == "user"]
            topic_msg = max(user_msgs, key=lambda m: len(set(m.lower().split()) - _FILLER), default=None)
            search_query = f"{topic_msg} {req.question}" if topic_msg else req.question
        else:
            search_query = req.question

        # Embed the query (cached)
        try:
            q_vec = _cached_embed(search_query)
        except Exception as e:
            yield f"data: {json.dumps({'type': 'error', 'message': str(e)})}\n\n"
            return

        # 2. Retrieve from Pinecone
        try:
            matches = query_index(_pc, q_vec, req.top_k)
        except Exception as e:
            yield f"data: {json.dumps({'type': 'error', 'message': str(e)})}\n\n"
            return

        # Filter out garbled/unreadable chunks and low-relevance results
        matches = [m for m in matches if _is_readable(m.get("text", ""))]
        if not matches:
            # No readable context — fall back to LLM general knowledge
            for delta in yield_chat(req.question, req.language):
                yield f"data: {json.dumps({'type': 'chunk', 'content': delta})}\n\n"
            yield f"data: {json.dumps({'type': 'done'})}\n\n"
            return

        # 3. Stream answer chunks
        try:
            history = [{"role": m.role, "content": m.content} for m in req.history[-6:]]
            for delta in yield_answer(req.question, matches, req.language, history):
                payload = json.dumps({"type": "chunk", "content": delta})
                yield f"data: {payload}\n\n"
        except Exception as e:
            yield f"data: {json.dumps({'type': 'error', 'message': str(e)})}\n\n"
            return

        # 4. Send sources
        sources_payload = json.dumps({"type": "sources", "sources": matches})
        yield f"data: {sources_payload}\n\n"

        # 5. Done
        yield f"data: {json.dumps({'type': 'done'})}\n\n"

    return StreamingResponse(event_stream(), media_type="text/event-stream")


@app.get("/api/sources")
def list_sources():
    """
    Return a list of unique source documents stored in Pinecone.
    Groups chunks by source filename and returns metadata.
    """
    global _sources_cache
    if _sources_cache is not None:
        return {"sources": _sources_cache}

    try:
        index = _pc.Index(_config.PINECONE_INDEX_NAME)
        # Use a dummy zero vector to fetch a broad sample of vectors
        zero_vec = [0.0] * _config.EMBEDDING_DIMENSION
        result = index.query(
            vector=zero_vec,
            top_k=10000,
            include_metadata=True,
        )
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

    # Group by source
    grouped: dict[str, dict] = defaultdict(lambda: {"modality": "unknown", "pages": set()})
    for match in result.get("matches", []):
        meta = match.get("metadata", {})
        src = meta.get("source", "unknown")
        grouped[src]["modality"] = meta.get("modality", "unknown")
        page = meta.get("page_number")
        if page is not None:
            grouped[src]["pages"].add(page)

    sources = [
        {
            "source": src,
            "modality": info["modality"],
            "page_count": len(info["pages"]) or 1,
            "url": _drive_map.get(src),
        }
        for src, info in sorted(grouped.items())
    ]
    _sources_cache = sources
    return {"sources": sources}


@app.post("/api/quiz")
def quiz(req: QuizRequest):
    """Generate a set of MCQ questions for the requested topic and difficulty."""
    if not req.topic.strip():
        raise HTTPException(status_code=400, detail="topic must not be empty")
    if req.num_questions < 1 or req.num_questions > 20:
        raise HTTPException(status_code=400, detail="num_questions must be 1–20")

    # Retrieve relevant context for the topic
    try:
        q_vec = embed_query(req.topic)
        matches = query_index(_pc, q_vec, top_k=8)
        matches = [m for m in matches if _is_readable(m.get("text", ""))]
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Retrieval error: {e}")

    try:
        questions = generate_quiz(req.topic, req.difficulty, req.num_questions, matches, req.language)
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Quiz generation error: {e}")

    return {"questions": questions}


def _gdrive_preview(file_id: str) -> str:
    return f"https://drive.google.com/file/d/{file_id}/preview"

def _extract_id(url: str) -> str:
    return url.split("/d/")[1].split("/")[0]

_GDRIVE_PAPERS = [
    {
        "name": "2018 — Breadth In Physics",
        "questions_url": _gdrive_preview(_extract_id("https://drive.google.com/file/d/1_wkxWixUrwFJXgaTksFx3sTXcqP2e-uE/view")),
        "markscheme_url": _gdrive_preview(_extract_id("https://drive.google.com/file/d/1UvupOzXARf2ZN1S75WAwG2po4mZ9vcpy/view")),
    },
    {
        "name": "2019 — Breadth In Physics",
        "questions_url": _gdrive_preview(_extract_id("https://drive.google.com/file/d/1Uu_u2kTqY8H3hoO4mZCsm-rKxoYq8B33/view")),
        "markscheme_url": _gdrive_preview(_extract_id("https://drive.google.com/file/d/1AhQW81K61Q6XguQrKdmwykYGcCAy7TDO/view")),
    },
    {
        "name": "2020 — Breadth In Physics",
        "questions_url": _gdrive_preview(_extract_id("https://drive.google.com/file/d/1IBTarByuPdhQu8PToDIyrZNOryPSYZpZ/view")),
        "markscheme_url": _gdrive_preview(_extract_id("https://drive.google.com/file/d/1pl3C3TIA6ypy2wKOhOjUVp6IOY12xt8j/view")),
    },
    {
        "name": "2021 — Breadth In Physics",
        "questions_url": _gdrive_preview(_extract_id("https://drive.google.com/file/d/15SMbGaz4eq40aTXbpHt2KLc4PQcoPtK2/view")),
        "markscheme_url": _gdrive_preview(_extract_id("https://drive.google.com/file/d/1l7q-6Im7Y_cjuaCGrP82ZSfeP8eeXOFT/view")),
    },
    {
        "name": "2022 — Breadth In Physics",
        "questions_url": _gdrive_preview(_extract_id("https://drive.google.com/file/d/1SE860PhZEETnRYn1laLkkkR5wS2sFGAr/view")),
        "markscheme_url": _gdrive_preview(_extract_id("https://drive.google.com/file/d/1TXh1DbawL7Svel7s7sZU4JlmkFCo6H9B/view")),
    },
    {
        "name": "2023 — Breadth In Physics",
        "questions_url": _gdrive_preview(_extract_id("https://drive.google.com/file/d/12UfI7i5clKqI7Bn9g0P93fBK3zbACwNn/view")),
        "markscheme_url": _gdrive_preview(_extract_id("https://drive.google.com/file/d/1yKiIYHIV7OwAtXCslQfJvsfP_1MAYkqx/view")),
    },
    {
        "name": "2024 — Breadth In Physics",
        "questions_url": _gdrive_preview(_extract_id("https://drive.google.com/file/d/1aSnms7-leYjh9MtNcOqrxwJWsBMTx0am/view")),
        "markscheme_url": _gdrive_preview(_extract_id("https://drive.google.com/file/d/1qgNkHOjEmfRVjX-BO8DMmDstNeTEsMQl/view")),
    },
]

@app.get("/api/papers")
def list_papers():
    """Return paired question + mark scheme PDFs hosted on Google Drive."""
    results = _GDRIVE_PAPERS

    return {"papers": sorted(results, key=lambda x: x["name"])}
